# Generated by Django 3.2.3 on 2021-05-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='address',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billing',
            name='cardname',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='billing',
            name='cardnumber',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billing',
            name='city',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='billing',
            name='emailid',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='billing',
            name='fullname',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='billing',
            name='state',
            field=models.TextField(max_length=80),
        ),
    ]
