# Generated by Django 3.2.3 on 2021-06-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendence',
            name='inTime',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyattendence',
            name='outTime',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='empattendence',
            name='dayOne',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empattendence',
            name='dayThree',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empattendence',
            name='dayTwo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='totalattendence',
            name='July',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='totalattendence',
            name='June',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='totalattendence',
            name='May',
            field=models.IntegerField(default=0),
        ),
    ]
