# Generated by Django 3.2.3 on 2021-06-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_emptable_designation'),
        ('Management', '0002_auto_20210602_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendence',
            name='empId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.emptable'),
        ),
    ]
