# Generated by Django 3.2.3 on 2021-06-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_emptable_designation'),
        ('Management', '0003_alter_dailyattendence_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empattendence',
            name='empId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.emptable'),
        ),
        migrations.AlterField(
            model_name='totalattendence',
            name='empId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.emptable'),
        ),
    ]
