# Generated by Django 3.2.3 on 2021-06-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_auto_20210602_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empattendence',
            name='dayOne',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='empattendence',
            name='dayThree',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='empattendence',
            name='dayTwo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='totalattendence',
            name='July',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='totalattendence',
            name='June',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='totalattendence',
            name='May',
            field=models.FloatField(default=0),
        ),
    ]
