# Generated by Django 3.2.3 on 2021-06-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_auto_20210603_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='empattendence',
            name='dayFive',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='empattendence',
            name='dayFour',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='empattendence',
            name='daySix',
            field=models.FloatField(default=0),
        ),
    ]
