# Generated by Django 3.2.3 on 2021-06-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_emptable_designation'),
        ('Management', '0006_auto_20210604_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dailyAttendence',
            new_name='dailyAttendance',
        ),
        migrations.RenameModel(
            old_name='empAttendence',
            new_name='empAttendance',
        ),
        migrations.RenameModel(
            old_name='totalAttendence',
            new_name='totalAttendance',
        ),
    ]
