# Generated by Django 3.2.3 on 2021-05-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upperwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.TextField()),
                ('upper_id', models.TextField()),
                ('upper_name', models.TextField()),
                ('upper_type', models.TextField()),
                ('price', models.TextField()),
                ('available', models.TextField()),
            ],
        ),
    ]
