# Generated by Django 3.2.3 on 2021-05-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_footwear_lowererwear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.TextField()),
                ('prod_img', models.ImageField(upload_to='productimg')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_type', models.TextField(max_length=50)),
                ('price', models.FloatField()),
                ('available', models.TextField()),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='footwear',
        ),
        migrations.DeleteModel(
            name='lowererwear',
        ),
        migrations.DeleteModel(
            name='upperwear',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.user'),
        ),
        migrations.AddField(
            model_name='cart',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.user'),
        ),
    ]
