# Generated by Django 3.2.3 on 2021-05-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_type',
        ),
    ]
