# Generated by Django 3.2.3 on 2021-05-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emptable',
            name='password',
            field=models.IntegerField(default=12345),
        ),
    ]
