# Generated by Django 3.2.3 on 2021-05-20 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderImport_id', models.IntegerField()),
                ('order_date', models.DateTimeField(verbose_name='Date of import request')),
                ('import_product', models.CharField(max_length=20)),
                ('orderImport_country', models.CharField(max_length=20)),
                ('status_of_import', models.CharField(max_length=20)),
                ('total_cost', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=20)),
                ('price_per_piece', models.FloatField(max_length=20)),
                ('shipping_cost', models.FloatField(max_length=20)),
                ('estimated_dateOfDelivery', models.DateField()),
                ('product_name', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='Import.import')),
            ],
        ),
    ]
