# Generated by Django 3.2.3 on 2021-05-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Import', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='status_of_import',
            field=models.CharField(choices=[('Pending', 'No'), ('Completed', 'Yes')], max_length=10),
        ),
    ]
