# Generated by Django 3.2.3 on 2021-05-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Import', '0003_alter_import_status_of_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='order_date',
            field=models.DateField(verbose_name='Date of import request'),
        ),
    ]
