# Generated by Django 3.2.3 on 2021-05-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='order_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='imported',
            name='order_ID',
            field=models.IntegerField(),
        ),
    ]
